-- ============================================================
-- Similar Callsign Monitoring System - Sample Data
-- ============================================================
-- Oracle 11g compatible
-- Date format: 'YYYY-MM-DD HH24:MI:SS'
-- ============================================================

-- Clear existing sample data (optional)
-- DELETE FROM T_SIMILAR_CALLSIGN_PAIR_REPORT;
-- DELETE FROM T_SIMILAR_CALLSIGN_PAIR;

-- ============================================================
-- Sample Data: T_SIMILAR_CALLSIGN_PAIR
-- Active pairs (CLEARED = '9999-12-31 23:59:59')
-- ============================================================

-- High similarity examples (SIMILARITY > 2) - Critical
INSERT INTO T_SIMILAR_CALLSIGN_PAIR (IDX, DETECTED, CLEARED, CCP, FP1_CALLSIGN, FP1_DEPT, FP1_DEST, FP1_EOBT, FP1_FID, FP1_ALT, FP2_CALLSIGN, FP2_DEPT, FP2_DEST, FP2_EOBT, FP2_FID, FP2_ALT, AOD_MATCH, FID_LEN_MATCH, MATCH_POS, MATCH_LEN, COMP_RAT, SIMILARITY, CTRL_PEAK, SCORE_PEAK, MARK)
VALUES (1, TO_CHAR(SYSDATE - 0.01, 'YYYY-MM-DD HH24:MI:SS'), '9999-12-31 23:59:59', 'T1E', 'KAL123', 'RKSI', 'RJTT', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'KE123', 'FL350', 'KAL124', 'RKSI', 'RJAA', TO_CHAR(SYSDATE + 0.01, 'YYYY-MM-DD HH24:MI:SS'), 'KE124', 'FL350', 'Y', 'Y', 1, 5, 0.95, 2.5, 85.5, 45.2, NULL);

INSERT INTO T_SIMILAR_CALLSIGN_PAIR (IDX, DETECTED, CLEARED, CCP, FP1_CALLSIGN, FP1_DEPT, FP1_DEST, FP1_EOBT, FP1_FID, FP1_ALT, FP2_CALLSIGN, FP2_DEPT, FP2_DEST, FP2_EOBT, FP2_FID, FP2_ALT, AOD_MATCH, FID_LEN_MATCH, MATCH_POS, MATCH_LEN, COMP_RAT, SIMILARITY, CTRL_PEAK, SCORE_PEAK, MARK)
VALUES (2, TO_CHAR(SYSDATE - 0.02, 'YYYY-MM-DD HH24:MI:SS'), '9999-12-31 23:59:59', 'T2W', 'AAR456', 'RKPK', 'RKSI', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'OZ456', 'FL280', 'AAR457', 'RKPK', 'RKSI', TO_CHAR(SYSDATE + 0.02, 'YYYY-MM-DD HH24:MI:SS'), 'OZ457', 'FL290', 'Y', 'Y', 1, 5, 0.92, 2.8, 90.2, 52.1, NULL);

INSERT INTO T_SIMILAR_CALLSIGN_PAIR (IDX, DETECTED, CLEARED, CCP, FP1_CALLSIGN, FP1_DEPT, FP1_DEST, FP1_EOBT, FP1_FID, FP1_ALT, FP2_CALLSIGN, FP2_DEPT, FP2_DEST, FP2_EOBT, FP2_FID, FP2_ALT, AOD_MATCH, FID_LEN_MATCH, MATCH_POS, MATCH_LEN, COMP_RAT, SIMILARITY, CTRL_PEAK, SCORE_PEAK, MARK)
VALUES (3, TO_CHAR(SYSDATE - 0.03, 'YYYY-MM-DD HH24:MI:SS'), '9999-12-31 23:59:59', 'D1', 'JNA789', 'RKSS', 'RKPC', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'JN789', 'FL200', 'JNA798', 'RKSS', 'RKTN', TO_CHAR(SYSDATE + 0.01, 'YYYY-MM-DD HH24:MI:SS'), 'JN798', 'FL210', 'N', 'Y', 1, 5, 0.88, 2.3, 78.4, 41.5, NULL);

-- Medium similarity examples (SIMILARITY 1-2) - Caution
INSERT INTO T_SIMILAR_CALLSIGN_PAIR (IDX, DETECTED, CLEARED, CCP, FP1_CALLSIGN, FP1_DEPT, FP1_DEST, FP1_EOBT, FP1_FID, FP1_ALT, FP2_CALLSIGN, FP2_DEPT, FP2_DEST, FP2_EOBT, FP2_FID, FP2_ALT, AOD_MATCH, FID_LEN_MATCH, MATCH_POS, MATCH_LEN, COMP_RAT, SIMILARITY, CTRL_PEAK, SCORE_PEAK, MARK)
VALUES (4, TO_CHAR(SYSDATE - 0.04, 'YYYY-MM-DD HH24:MI:SS'), '9999-12-31 23:59:59', 'T1E', 'TWB301', 'RKSI', 'VHHH', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'TW301', 'FL370', 'TWB310', 'RKSI', 'ZSSS', TO_CHAR(SYSDATE + 0.02, 'YYYY-MM-DD HH24:MI:SS'), 'TW310', 'FL380', 'Y', 'Y', 1, 4, 0.75, 1.5, 55.3, 25.8, NULL);

INSERT INTO T_SIMILAR_CALLSIGN_PAIR (IDX, DETECTED, CLEARED, CCP, FP1_CALLSIGN, FP1_DEPT, FP1_DEST, FP1_EOBT, FP1_FID, FP1_ALT, FP2_CALLSIGN, FP2_DEPT, FP2_DEST, FP2_EOBT, FP2_FID, FP2_ALT, AOD_MATCH, FID_LEN_MATCH, MATCH_POS, MATCH_LEN, COMP_RAT, SIMILARITY, CTRL_PEAK, SCORE_PEAK, MARK)
VALUES (5, TO_CHAR(SYSDATE - 0.05, 'YYYY-MM-DD HH24:MI:SS'), '9999-12-31 23:59:59', 'A1', 'ABL512', 'RKSS', 'RKSI', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'AB512', 'FL150', 'ABL521', 'RKSS', 'RKSI', TO_CHAR(SYSDATE + 0.01, 'YYYY-MM-DD HH24:MI:SS'), 'AB521', 'FL160', 'Y', 'Y', 1, 4, 0.72, 1.8, 62.1, 28.4, NULL);

INSERT INTO T_SIMILAR_CALLSIGN_PAIR (IDX, DETECTED, CLEARED, CCP, FP1_CALLSIGN, FP1_DEPT, FP1_DEST, FP1_EOBT, FP1_FID, FP1_ALT, FP2_CALLSIGN, FP2_DEPT, FP2_DEST, FP2_EOBT, FP2_FID, FP2_ALT, AOD_MATCH, FID_LEN_MATCH, MATCH_POS, MATCH_LEN, COMP_RAT, SIMILARITY, CTRL_PEAK, SCORE_PEAK, MARK)
VALUES (6, TO_CHAR(SYSDATE - 0.06, 'YYYY-MM-DD HH24:MI:SS'), '9999-12-31 23:59:59', 'T2W', 'CPA888', 'VHHH', 'RKSI', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'CX888', 'FL390', 'CPA889', 'VHHH', 'RKSS', TO_CHAR(SYSDATE + 0.02, 'YYYY-MM-DD HH24:MI:SS'), 'CX889', 'FL400', 'N', 'Y', 1, 5, 0.68, 1.2, 48.7, 22.3, NULL);

-- Low similarity examples (SIMILARITY <= 1) - Monitor
INSERT INTO T_SIMILAR_CALLSIGN_PAIR (IDX, DETECTED, CLEARED, CCP, FP1_CALLSIGN, FP1_DEPT, FP1_DEST, FP1_EOBT, FP1_FID, FP1_ALT, FP2_CALLSIGN, FP2_DEPT, FP2_DEST, FP2_EOBT, FP2_FID, FP2_ALT, AOD_MATCH, FID_LEN_MATCH, MATCH_POS, MATCH_LEN, COMP_RAT, SIMILARITY, CTRL_PEAK, SCORE_PEAK, MARK)
VALUES (7, TO_CHAR(SYSDATE - 0.07, 'YYYY-MM-DD HH24:MI:SS'), '9999-12-31 23:59:59', 'D1', 'ESR101', 'RKSI', 'RKPC', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'OZ101', 'FL250', 'ESR110', 'RKSI', 'RKPK', TO_CHAR(SYSDATE + 0.03, 'YYYY-MM-DD HH24:MI:SS'), 'OZ110', 'FL260', 'N', 'Y', 1, 3, 0.55, 0.8, 32.4, 15.2, NULL);

INSERT INTO T_SIMILAR_CALLSIGN_PAIR (IDX, DETECTED, CLEARED, CCP, FP1_CALLSIGN, FP1_DEPT, FP1_DEST, FP1_EOBT, FP1_FID, FP1_ALT, FP2_CALLSIGN, FP2_DEPT, FP2_DEST, FP2_EOBT, FP2_FID, FP2_ALT, AOD_MATCH, FID_LEN_MATCH, MATCH_POS, MATCH_LEN, COMP_RAT, SIMILARITY, CTRL_PEAK, SCORE_PEAK, MARK)
VALUES (8, TO_CHAR(SYSDATE - 0.08, 'YYYY-MM-DD HH24:MI:SS'), '9999-12-31 23:59:59', 'A1', 'JJA202', 'RKPC', 'RKSI', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), '7C202', 'FL180', 'JJA220', 'RKPK', 'RKSI', TO_CHAR(SYSDATE + 0.02, 'YYYY-MM-DD HH24:MI:SS'), '7C220', 'FL190', 'Y', 'N', 1, 3, 0.48, 0.6, 28.1, 12.8, NULL);

INSERT INTO T_SIMILAR_CALLSIGN_PAIR (IDX, DETECTED, CLEARED, CCP, FP1_CALLSIGN, FP1_DEPT, FP1_DEST, FP1_EOBT, FP1_FID, FP1_ALT, FP2_CALLSIGN, FP2_DEPT, FP2_DEST, FP2_EOBT, FP2_FID, FP2_ALT, AOD_MATCH, FID_LEN_MATCH, MATCH_POS, MATCH_LEN, COMP_RAT, SIMILARITY, CTRL_PEAK, SCORE_PEAK, MARK)
VALUES (9, TO_CHAR(SYSDATE - 0.09, 'YYYY-MM-DD HH24:MI:SS'), '9999-12-31 23:59:59', 'T1E', 'KAL777', 'RKSI', 'KLAX', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'KE777', 'FL410', 'KAL707', 'RKSI', 'KJFK', TO_CHAR(SYSDATE + 0.01, 'YYYY-MM-DD HH24:MI:SS'), 'KE707', 'FL400', 'Y', 'Y', 1, 4, 0.52, 0.9, 35.6, 18.4, NULL);

INSERT INTO T_SIMILAR_CALLSIGN_PAIR (IDX, DETECTED, CLEARED, CCP, FP1_CALLSIGN, FP1_DEPT, FP1_DEST, FP1_EOBT, FP1_FID, FP1_ALT, FP2_CALLSIGN, FP2_DEPT, FP2_DEST, FP2_EOBT, FP2_FID, FP2_ALT, AOD_MATCH, FID_LEN_MATCH, MATCH_POS, MATCH_LEN, COMP_RAT, SIMILARITY, CTRL_PEAK, SCORE_PEAK, MARK)
VALUES (10, TO_CHAR(SYSDATE - 0.10, 'YYYY-MM-DD HH24:MI:SS'), '9999-12-31 23:59:59', 'T2W', 'AAR333', 'RKSI', 'RCTP', TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 'OZ333', 'FL350', 'AAR303', 'RKSI', 'RCSS', TO_CHAR(SYSDATE + 0.02, 'YYYY-MM-DD HH24:MI:SS'), 'OZ303', 'FL360', 'Y', 'Y', 1, 4, 0.58, 1.0, 38.2, 19.5, NULL);

-- Cleared (historical) pairs for statistics
INSERT INTO T_SIMILAR_CALLSIGN_PAIR (IDX, DETECTED, CLEARED, CCP, FP1_CALLSIGN, FP1_DEPT, FP1_DEST, FP1_EOBT, FP1_FID, FP1_ALT, FP2_CALLSIGN, FP2_DEPT, FP2_DEST, FP2_EOBT, FP2_FID, FP2_ALT, AOD_MATCH, FID_LEN_MATCH, MATCH_POS, MATCH_LEN, COMP_RAT, SIMILARITY, CTRL_PEAK, SCORE_PEAK, MARK)
VALUES (11, TO_CHAR(SYSDATE - 1, 'YYYY-MM-DD HH24:MI:SS'), TO_CHAR(SYSDATE - 0.5, 'YYYY-MM-DD HH24:MI:SS'), 'T1E', 'KAL001', 'RKSI', 'RJTT', TO_CHAR(SYSDATE - 1, 'YYYY-MM-DD HH24:MI:SS'), 'KE001', 'FL330', 'KAL011', 'RKSI', 'RJAA', TO_CHAR(SYSDATE - 0.9, 'YYYY-MM-DD HH24:MI:SS'), 'KE011', 'FL340', 'Y', 'Y', 1, 4, 0.82, 2.1, 72.3, 38.5, NULL);

INSERT INTO T_SIMILAR_CALLSIGN_PAIR (IDX, DETECTED, CLEARED, CCP, FP1_CALLSIGN, FP1_DEPT, FP1_DEST, FP1_EOBT, FP1_FID, FP1_ALT, FP2_CALLSIGN, FP2_DEPT, FP2_DEST, FP2_EOBT, FP2_FID, FP2_ALT, AOD_MATCH, FID_LEN_MATCH, MATCH_POS, MATCH_LEN, COMP_RAT, SIMILARITY, CTRL_PEAK, SCORE_PEAK, MARK)
VALUES (12, TO_CHAR(SYSDATE - 2, 'YYYY-MM-DD HH24:MI:SS'), TO_CHAR(SYSDATE - 1.5, 'YYYY-MM-DD HH24:MI:SS'), 'D1', 'TWB505', 'RKSI', 'ZSSS', TO_CHAR(SYSDATE - 2, 'YYYY-MM-DD HH24:MI:SS'), 'TW505', 'FL370', 'TWB550', 'RKSI', 'ZSPD', TO_CHAR(SYSDATE - 1.9, 'YYYY-MM-DD HH24:MI:SS'), 'TW550', 'FL380', 'Y', 'Y', 1, 4, 0.65, 1.4, 52.1, 24.8, NULL);

-- ============================================================
-- Sample Data: T_SIMILAR_CALLSIGN_PAIR_REPORT
-- ============================================================

-- Report for critical similarity case (Controller error)
INSERT INTO T_SIMILAR_CALLSIGN_PAIR_REPORT (IDX, REPORTED, REPORTER, AO, TYPE, TYPE_DETAIL, REMARK)
VALUES (11, TO_CHAR(SYSDATE - 0.4, 'YYYY-MM-DD HH24:MI:SS'), 'Controller A', 1, 1, 2, 'Issued clearance to wrong aircraft. Corrected after pilot query.');

-- Report for readback error
INSERT INTO T_SIMILAR_CALLSIGN_PAIR_REPORT (IDX, REPORTED, REPORTER, AO, TYPE, TYPE_DETAIL, REMARK)
VALUES (12, TO_CHAR(SYSDATE - 1.4, 'YYYY-MM-DD HH24:MI:SS'), 'Controller B', 2, 3, 1, 'Pilot readback with wrong callsign. Detected and corrected immediately.');

-- Report for pilot error
INSERT INTO T_SIMILAR_CALLSIGN_PAIR_REPORT (IDX, REPORTED, REPORTER, AO, TYPE, TYPE_DETAIL, REMARK)
VALUES (11, TO_CHAR(SYSDATE - 0.3, 'YYYY-MM-DD HH24:MI:SS'), 'Controller A', 2, 2, 1, 'Follow-up report: Pilot acknowledged wrong callsign initially.');

-- Update sequence to continue after sample data
ALTER SEQUENCE SEQ_SIMILAR_CALLSIGN_PAIR INCREMENT BY 1;
SELECT SEQ_SIMILAR_CALLSIGN_PAIR.NEXTVAL FROM DUAL;
-- Run this 12 times or use: ALTER SEQUENCE SEQ_SIMILAR_CALLSIGN_PAIR RESTART START WITH 13;

-- For Oracle 11g, manually set sequence (run these individually)
-- DROP SEQUENCE SEQ_SIMILAR_CALLSIGN_PAIR;
-- CREATE SEQUENCE SEQ_SIMILAR_CALLSIGN_PAIR START WITH 13 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMIT;

-- ============================================================
-- Verification queries
-- ============================================================
-- SELECT COUNT(*) as TOTAL_PAIRS FROM T_SIMILAR_CALLSIGN_PAIR;
-- SELECT COUNT(*) as ACTIVE_PAIRS FROM T_SIMILAR_CALLSIGN_PAIR WHERE CLEARED = '9999-12-31 23:59:59';
-- SELECT COUNT(*) as TOTAL_REPORTS FROM T_SIMILAR_CALLSIGN_PAIR_REPORT;
-- SELECT CCP, COUNT(*) as CNT FROM T_SIMILAR_CALLSIGN_PAIR WHERE CLEARED = '9999-12-31 23:59:59' GROUP BY CCP;
